export const apiEndPoints = {
        // developer end points
        developerotp: '/api/developer/developerotp',
        resendotp: '/api/developer/resendotp',
        forgetOtp: '/api/developer/developerforgetOtp',
        forgetresendotp: '/api/developer/forgetresendotp',
        getStartNowStatus: '/api/developer/getStartNowStatus',
        getPaymentOption: '/api/developer/getPaymentOption',
        paySubscription: '/api/developer/paySubscription',
        verifyPayment: '/api/developer/verifyPayment',
        getSubData: '/api/developer/getSubData',
        PayHistory: '/api/developer/payHistoryData',
        getUserChatList: '/api/developer/getUserChatList',
        Room: '/api/developer/Room',
        developerNewMessage: '/api/developer/developerNewMessage',
        checkNotifications: 'api/developer/checkNotifications',
        clearNotification: 'api/developer/clearNotifications',
        getnotificationCounts: 'api/developer/notificationCounts',
        clearAllNotification: 'api/developer/clearAllNotification',
        fetchDeveloperName: '/api/developer/fetchName',
        developerregister:'/api/developer/developerregister',
        getDeveloperProfile:'/api/developer/getProfile',
        developerlogin:"/api/developer/developerlogin",
        DeveloperformData:'/api/developer/developerDetailedDataEdit',
        developerData:'/api/developer/developerData',
        developerresetPassword:'/api/developer/developerresetPassword',
        developerforgetPassword:'/api/developer/developerforgetPassword',
        // user end points
        userResendotp: '/api/user/userResendotp',
        getdeveloperdataList: '/api/user/getdeveloperdataList',
        getdeveloperView: '/api/user/getdeveloperView',
        developerFollowersUpdate: '/api/user/developerFollowersUpdate',
        getfollowingData: '/api/user/getfollowingData',
        postCommentAndRating: '/api/user/postCommentAndRating',
        getMessages: '/api/user/Messages',
        sendNewMessage: '/api/user/sendNewMessage',
        getChatList: '/api/user/getChatList',
        fetchUserName: '/api/user/fetchData',
        postRegisterData:'/api/user/register',
        postUserOtp:'/api/user/otp',
        UserLogin:'/api/user/login',
        UserresetPassword:'/api/user/resetPassword',
        sendDataForReset:'/api/user/forgetOtp',
        userForgetPassword:"/api/user/forgetPassword",
        updateImage:'/api/user/updateImage',
        editUserData :'/api/user/editData',
        getUserProfile:'/api/user/getProfile',



        //    admin end points
        developerRequestData: '/api/admin/developerRequestData',
        developerDetailedView: '/api/admin/developerDetailedView',
        developerRequestAction: '/api/admin/developerRequestAction',
        getDeveloperSubscriptionDetails: '/api/admin/getDeveloperSubscriptionDetails',
        adminCreateBanner: '/api/admin/adminCreateBanner',
        getBannerData: '/api/admin/getBannerData',
        handlingBanner: '/api/admin/handlingBanner',
        getDataToDash: '/api/admin/getDataToDash',
        PlanData: '/api/admin/PlanData',
        deletePlan: '/api/admin/deletePlan',
        addPlan: '/api/admin/addPlan',
        adminlogin:'/api/admin/adminlogin',
        getuserdetails:'/api/admin/getuserdetails',
        blockuser:'/api/admin/blockuser',
        developerdetails:'/api/admin/developerdetails',
        blockdeveloper:'/api/admin/blockdeveloper',

}
